# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-05 09:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text=b'Title of the Article', max_length=255, unique=True)),
                ('slug', models.SlugField()),
                ('is_published', models.BooleanField(default=False, help_text=b'Do you want to publish this article ?')),
                ('published_at', models.DateTimeField(help_text=b'Date the article was published at')),
                ('body', models.TextField()),
                ('hero_image', models.ImageField(blank=True, help_text=b'Hero image for the blog', null=True, upload_to=b'hero')),
                ('content_image', models.ImageField(blank=True, help_text=b'optional image to be included in the content', null=True, upload_to=b'content')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-updated_at'],
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(help_text=b'Category this article belongs to', on_delete=django.db.models.deletion.CASCADE, to='articles.Category'),
        ),
    ]
